// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejz2xRzdpVWO_EumC9hxk1N6V8T18cwY',
    appId: '1:885070725547:web:04d88979d78c2fcc7c92ee',
    messagingSenderId: '885070725547',
    projectId: 'teste-54a29',
    authDomain: 'teste-54a29.firebaseapp.com',
    storageBucket: 'teste-54a29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESx3YyKdJ64QkrQ-NmGAgcbuwixduDdI',
    appId: '1:885070725547:android:e851f45ecc75ea527c92ee',
    messagingSenderId: '885070725547',
    projectId: 'teste-54a29',
    storageBucket: 'teste-54a29.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAejz2xRzdpVWO_EumC9hxk1N6V8T18cwY',
    appId: '1:885070725547:web:d68f95b9d93e7a0b7c92ee',
    messagingSenderId: '885070725547',
    projectId: 'teste-54a29',
    authDomain: 'teste-54a29.firebaseapp.com',
    storageBucket: 'teste-54a29.firebasestorage.app',
  );
}
